// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fish_crazy_protocol.proto

#ifndef PROTOBUF_fish_5fcrazy_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_fish_5fcrazy_5fprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "fish_crazy_def.pb.h"
#include "msg_type_def.pb.h"
// @@protoc_insertion_point(includes)

namespace fish_protocols {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_fish_5fcrazy_5fprotocol_2eproto();
void protobuf_AssignDesc_fish_5fcrazy_5fprotocol_2eproto();
void protobuf_ShutdownFile_fish_5fcrazy_5fprotocol_2eproto();

class msg_item;
class packetc2l_leave_table;
class packetl2c_leave_table_result;
class packetc2l_check_state;
class packetl2c_check_state_result;
class packetc2l_use_item;
class packetl2c_use_item_result;

// ===================================================================

class msg_item : public ::google::protobuf::Message {
 public:
  msg_item();
  virtual ~msg_item();

  msg_item(const msg_item& from);

  inline msg_item& operator=(const msg_item& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const msg_item& default_instance();

  void Swap(msg_item* other);

  // implements Message ----------------------------------------------

  msg_item* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const msg_item& from);
  void MergeFrom(const msg_item& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 item_id = 1;
  inline bool has_item_id() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 1;
  inline ::google::protobuf::int32 item_id() const;
  inline void set_item_id(::google::protobuf::int32 value);

  // optional int32 item_count = 2;
  inline bool has_item_count() const;
  inline void clear_item_count();
  static const int kItemCountFieldNumber = 2;
  inline ::google::protobuf::int32 item_count() const;
  inline void set_item_count(::google::protobuf::int32 value);

  // optional int32 end_time = 3;
  inline bool has_end_time() const;
  inline void clear_end_time();
  static const int kEndTimeFieldNumber = 3;
  inline ::google::protobuf::int32 end_time() const;
  inline void set_end_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fish_protocols.msg_item)
 private:
  inline void set_has_item_id();
  inline void clear_has_item_id();
  inline void set_has_item_count();
  inline void clear_has_item_count();
  inline void set_has_end_time();
  inline void clear_has_end_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 item_id_;
  ::google::protobuf::int32 item_count_;
  ::google::protobuf::int32 end_time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_fish_5fcrazy_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static msg_item* default_instance_;
};
// -------------------------------------------------------------------

class packetc2l_leave_table : public ::google::protobuf::Message {
 public:
  packetc2l_leave_table();
  virtual ~packetc2l_leave_table();

  packetc2l_leave_table(const packetc2l_leave_table& from);

  inline packetc2l_leave_table& operator=(const packetc2l_leave_table& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packetc2l_leave_table& default_instance();

  void Swap(packetc2l_leave_table* other);

  // implements Message ----------------------------------------------

  packetc2l_leave_table* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packetc2l_leave_table& from);
  void MergeFrom(const packetc2l_leave_table& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_c2l_leave_table];
  inline bool has_packet_id() const;
  inline void clear_packet_id();
  static const int kPacketIdFieldNumber = 1;
  inline ::fish_protocols::e_server_msg_type packet_id() const;
  inline void set_packet_id(::fish_protocols::e_server_msg_type value);

  // @@protoc_insertion_point(class_scope:fish_protocols.packetc2l_leave_table)
 private:
  inline void set_has_packet_id();
  inline void clear_has_packet_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int packet_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_fish_5fcrazy_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static packetc2l_leave_table* default_instance_;
};
// -------------------------------------------------------------------

class packetl2c_leave_table_result : public ::google::protobuf::Message {
 public:
  packetl2c_leave_table_result();
  virtual ~packetl2c_leave_table_result();

  packetl2c_leave_table_result(const packetl2c_leave_table_result& from);

  inline packetl2c_leave_table_result& operator=(const packetl2c_leave_table_result& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packetl2c_leave_table_result& default_instance();

  void Swap(packetl2c_leave_table_result* other);

  // implements Message ----------------------------------------------

  packetl2c_leave_table_result* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packetl2c_leave_table_result& from);
  void MergeFrom(const packetl2c_leave_table_result& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_l2c_leave_table_result];
  inline bool has_packet_id() const;
  inline void clear_packet_id();
  static const int kPacketIdFieldNumber = 1;
  inline ::fish_protocols::e_server_msg_type packet_id() const;
  inline void set_packet_id(::fish_protocols::e_server_msg_type value);

  // optional int64 sync_gold = 2;
  inline bool has_sync_gold() const;
  inline void clear_sync_gold();
  static const int kSyncGoldFieldNumber = 2;
  inline ::google::protobuf::int64 sync_gold() const;
  inline void set_sync_gold(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:fish_protocols.packetl2c_leave_table_result)
 private:
  inline void set_has_packet_id();
  inline void clear_has_packet_id();
  inline void set_has_sync_gold();
  inline void clear_has_sync_gold();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 sync_gold_;
  int packet_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_fish_5fcrazy_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static packetl2c_leave_table_result* default_instance_;
};
// -------------------------------------------------------------------

class packetc2l_check_state : public ::google::protobuf::Message {
 public:
  packetc2l_check_state();
  virtual ~packetc2l_check_state();

  packetc2l_check_state(const packetc2l_check_state& from);

  inline packetc2l_check_state& operator=(const packetc2l_check_state& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packetc2l_check_state& default_instance();

  void Swap(packetc2l_check_state* other);

  // implements Message ----------------------------------------------

  packetc2l_check_state* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packetc2l_check_state& from);
  void MergeFrom(const packetc2l_check_state& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_c2l_check_state];
  inline bool has_packet_id() const;
  inline void clear_packet_id();
  static const int kPacketIdFieldNumber = 1;
  inline ::fish_protocols::e_server_msg_type packet_id() const;
  inline void set_packet_id(::fish_protocols::e_server_msg_type value);

  // @@protoc_insertion_point(class_scope:fish_protocols.packetc2l_check_state)
 private:
  inline void set_has_packet_id();
  inline void clear_has_packet_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int packet_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_fish_5fcrazy_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static packetc2l_check_state* default_instance_;
};
// -------------------------------------------------------------------

class packetl2c_check_state_result : public ::google::protobuf::Message {
 public:
  packetl2c_check_state_result();
  virtual ~packetl2c_check_state_result();

  packetl2c_check_state_result(const packetl2c_check_state_result& from);

  inline packetl2c_check_state_result& operator=(const packetl2c_check_state_result& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packetl2c_check_state_result& default_instance();

  void Swap(packetl2c_check_state_result* other);

  // implements Message ----------------------------------------------

  packetl2c_check_state_result* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packetl2c_check_state_result& from);
  void MergeFrom(const packetl2c_check_state_result& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_l2c_check_state_result];
  inline bool has_packet_id() const;
  inline void clear_packet_id();
  static const int kPacketIdFieldNumber = 1;
  inline ::fish_protocols::e_server_msg_type packet_id() const;
  inline void set_packet_id(::fish_protocols::e_server_msg_type value);

  // optional bool is_intable = 2 [default = false];
  inline bool has_is_intable() const;
  inline void clear_is_intable();
  static const int kIsIntableFieldNumber = 2;
  inline bool is_intable() const;
  inline void set_is_intable(bool value);

  // repeated .fish_protocols.msg_item itemlist = 3;
  inline int itemlist_size() const;
  inline void clear_itemlist();
  static const int kItemlistFieldNumber = 3;
  inline const ::fish_protocols::msg_item& itemlist(int index) const;
  inline ::fish_protocols::msg_item* mutable_itemlist(int index);
  inline ::fish_protocols::msg_item* add_itemlist();
  inline const ::google::protobuf::RepeatedPtrField< ::fish_protocols::msg_item >&
      itemlist() const;
  inline ::google::protobuf::RepeatedPtrField< ::fish_protocols::msg_item >*
      mutable_itemlist();

  // optional int32 turret_id = 4;
  inline bool has_turret_id() const;
  inline void clear_turret_id();
  static const int kTurretIdFieldNumber = 4;
  inline ::google::protobuf::int32 turret_id() const;
  inline void set_turret_id(::google::protobuf::int32 value);

  // optional int32 gamelvl = 5;
  inline bool has_gamelvl() const;
  inline void clear_gamelvl();
  static const int kGamelvlFieldNumber = 5;
  inline ::google::protobuf::int32 gamelvl() const;
  inline void set_gamelvl(::google::protobuf::int32 value);

  // optional int32 gameexp = 6;
  inline bool has_gameexp() const;
  inline void clear_gameexp();
  static const int kGameexpFieldNumber = 6;
  inline ::google::protobuf::int32 gameexp() const;
  inline void set_gameexp(::google::protobuf::int32 value);

  // optional int32 getgift = 7;
  inline bool has_getgift() const;
  inline void clear_getgift();
  static const int kGetgiftFieldNumber = 7;
  inline ::google::protobuf::int32 getgift() const;
  inline void set_getgift(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fish_protocols.packetl2c_check_state_result)
 private:
  inline void set_has_packet_id();
  inline void clear_has_packet_id();
  inline void set_has_is_intable();
  inline void clear_has_is_intable();
  inline void set_has_turret_id();
  inline void clear_has_turret_id();
  inline void set_has_gamelvl();
  inline void clear_has_gamelvl();
  inline void set_has_gameexp();
  inline void clear_has_gameexp();
  inline void set_has_getgift();
  inline void clear_has_getgift();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int packet_id_;
  bool is_intable_;
  ::google::protobuf::RepeatedPtrField< ::fish_protocols::msg_item > itemlist_;
  ::google::protobuf::int32 turret_id_;
  ::google::protobuf::int32 gamelvl_;
  ::google::protobuf::int32 gameexp_;
  ::google::protobuf::int32 getgift_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_fish_5fcrazy_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static packetl2c_check_state_result* default_instance_;
};
// -------------------------------------------------------------------

class packetc2l_use_item : public ::google::protobuf::Message {
 public:
  packetc2l_use_item();
  virtual ~packetc2l_use_item();

  packetc2l_use_item(const packetc2l_use_item& from);

  inline packetc2l_use_item& operator=(const packetc2l_use_item& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packetc2l_use_item& default_instance();

  void Swap(packetc2l_use_item* other);

  // implements Message ----------------------------------------------

  packetc2l_use_item* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packetc2l_use_item& from);
  void MergeFrom(const packetc2l_use_item& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_c2l_use_item];
  inline bool has_packet_id() const;
  inline void clear_packet_id();
  static const int kPacketIdFieldNumber = 1;
  inline ::fish_protocols::e_server_msg_type packet_id() const;
  inline void set_packet_id(::fish_protocols::e_server_msg_type value);

  // optional int32 item_id = 2;
  inline bool has_item_id() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 2;
  inline ::google::protobuf::int32 item_id() const;
  inline void set_item_id(::google::protobuf::int32 value);

  // optional int32 pos_x = 3;
  inline bool has_pos_x() const;
  inline void clear_pos_x();
  static const int kPosXFieldNumber = 3;
  inline ::google::protobuf::int32 pos_x() const;
  inline void set_pos_x(::google::protobuf::int32 value);

  // optional int32 pos_y = 4;
  inline bool has_pos_y() const;
  inline void clear_pos_y();
  static const int kPosYFieldNumber = 4;
  inline ::google::protobuf::int32 pos_y() const;
  inline void set_pos_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fish_protocols.packetc2l_use_item)
 private:
  inline void set_has_packet_id();
  inline void clear_has_packet_id();
  inline void set_has_item_id();
  inline void clear_has_item_id();
  inline void set_has_pos_x();
  inline void clear_has_pos_x();
  inline void set_has_pos_y();
  inline void clear_has_pos_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int packet_id_;
  ::google::protobuf::int32 item_id_;
  ::google::protobuf::int32 pos_x_;
  ::google::protobuf::int32 pos_y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_fish_5fcrazy_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static packetc2l_use_item* default_instance_;
};
// -------------------------------------------------------------------

class packetl2c_use_item_result : public ::google::protobuf::Message {
 public:
  packetl2c_use_item_result();
  virtual ~packetl2c_use_item_result();

  packetl2c_use_item_result(const packetl2c_use_item_result& from);

  inline packetl2c_use_item_result& operator=(const packetl2c_use_item_result& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const packetl2c_use_item_result& default_instance();

  void Swap(packetl2c_use_item_result* other);

  // implements Message ----------------------------------------------

  packetl2c_use_item_result* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const packetl2c_use_item_result& from);
  void MergeFrom(const packetl2c_use_item_result& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_l2c_use_item_result];
  inline bool has_packet_id() const;
  inline void clear_packet_id();
  static const int kPacketIdFieldNumber = 1;
  inline ::fish_protocols::e_server_msg_type packet_id() const;
  inline void set_packet_id(::fish_protocols::e_server_msg_type value);

  // optional int32 item_id = 2;
  inline bool has_item_id() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 2;
  inline ::google::protobuf::int32 item_id() const;
  inline void set_item_id(::google::protobuf::int32 value);

  // optional .msg_type_def.e_msg_result_def result = 3 [default = e_rmt_fail];
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 3;
  inline ::msg_type_def::e_msg_result_def result() const;
  inline void set_result(::msg_type_def::e_msg_result_def value);

  // optional int32 item_count = 4 [default = 1];
  inline bool has_item_count() const;
  inline void clear_item_count();
  static const int kItemCountFieldNumber = 4;
  inline ::google::protobuf::int32 item_count() const;
  inline void set_item_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fish_protocols.packetl2c_use_item_result)
 private:
  inline void set_has_packet_id();
  inline void clear_has_packet_id();
  inline void set_has_item_id();
  inline void clear_has_item_id();
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_item_count();
  inline void clear_has_item_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int packet_id_;
  ::google::protobuf::int32 item_id_;
  int result_;
  ::google::protobuf::int32 item_count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_fish_5fcrazy_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_fish_5fcrazy_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static packetl2c_use_item_result* default_instance_;
};
// ===================================================================


// ===================================================================

// msg_item

// optional int32 item_id = 1;
inline bool msg_item::has_item_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void msg_item::set_has_item_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void msg_item::clear_has_item_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void msg_item::clear_item_id() {
  item_id_ = 0;
  clear_has_item_id();
}
inline ::google::protobuf::int32 msg_item::item_id() const {
  return item_id_;
}
inline void msg_item::set_item_id(::google::protobuf::int32 value) {
  set_has_item_id();
  item_id_ = value;
}

// optional int32 item_count = 2;
inline bool msg_item::has_item_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void msg_item::set_has_item_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void msg_item::clear_has_item_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void msg_item::clear_item_count() {
  item_count_ = 0;
  clear_has_item_count();
}
inline ::google::protobuf::int32 msg_item::item_count() const {
  return item_count_;
}
inline void msg_item::set_item_count(::google::protobuf::int32 value) {
  set_has_item_count();
  item_count_ = value;
}

// optional int32 end_time = 3;
inline bool msg_item::has_end_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void msg_item::set_has_end_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void msg_item::clear_has_end_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void msg_item::clear_end_time() {
  end_time_ = 0;
  clear_has_end_time();
}
inline ::google::protobuf::int32 msg_item::end_time() const {
  return end_time_;
}
inline void msg_item::set_end_time(::google::protobuf::int32 value) {
  set_has_end_time();
  end_time_ = value;
}

// -------------------------------------------------------------------

// packetc2l_leave_table

// optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_c2l_leave_table];
inline bool packetc2l_leave_table::has_packet_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packetc2l_leave_table::set_has_packet_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packetc2l_leave_table::clear_has_packet_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packetc2l_leave_table::clear_packet_id() {
  packet_id_ = 10003;
  clear_has_packet_id();
}
inline ::fish_protocols::e_server_msg_type packetc2l_leave_table::packet_id() const {
  return static_cast< ::fish_protocols::e_server_msg_type >(packet_id_);
}
inline void packetc2l_leave_table::set_packet_id(::fish_protocols::e_server_msg_type value) {
  assert(::fish_protocols::e_server_msg_type_IsValid(value));
  set_has_packet_id();
  packet_id_ = value;
}

// -------------------------------------------------------------------

// packetl2c_leave_table_result

// optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_l2c_leave_table_result];
inline bool packetl2c_leave_table_result::has_packet_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packetl2c_leave_table_result::set_has_packet_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packetl2c_leave_table_result::clear_has_packet_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packetl2c_leave_table_result::clear_packet_id() {
  packet_id_ = 15003;
  clear_has_packet_id();
}
inline ::fish_protocols::e_server_msg_type packetl2c_leave_table_result::packet_id() const {
  return static_cast< ::fish_protocols::e_server_msg_type >(packet_id_);
}
inline void packetl2c_leave_table_result::set_packet_id(::fish_protocols::e_server_msg_type value) {
  assert(::fish_protocols::e_server_msg_type_IsValid(value));
  set_has_packet_id();
  packet_id_ = value;
}

// optional int64 sync_gold = 2;
inline bool packetl2c_leave_table_result::has_sync_gold() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void packetl2c_leave_table_result::set_has_sync_gold() {
  _has_bits_[0] |= 0x00000002u;
}
inline void packetl2c_leave_table_result::clear_has_sync_gold() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void packetl2c_leave_table_result::clear_sync_gold() {
  sync_gold_ = GOOGLE_LONGLONG(0);
  clear_has_sync_gold();
}
inline ::google::protobuf::int64 packetl2c_leave_table_result::sync_gold() const {
  return sync_gold_;
}
inline void packetl2c_leave_table_result::set_sync_gold(::google::protobuf::int64 value) {
  set_has_sync_gold();
  sync_gold_ = value;
}

// -------------------------------------------------------------------

// packetc2l_check_state

// optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_c2l_check_state];
inline bool packetc2l_check_state::has_packet_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packetc2l_check_state::set_has_packet_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packetc2l_check_state::clear_has_packet_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packetc2l_check_state::clear_packet_id() {
  packet_id_ = 10004;
  clear_has_packet_id();
}
inline ::fish_protocols::e_server_msg_type packetc2l_check_state::packet_id() const {
  return static_cast< ::fish_protocols::e_server_msg_type >(packet_id_);
}
inline void packetc2l_check_state::set_packet_id(::fish_protocols::e_server_msg_type value) {
  assert(::fish_protocols::e_server_msg_type_IsValid(value));
  set_has_packet_id();
  packet_id_ = value;
}

// -------------------------------------------------------------------

// packetl2c_check_state_result

// optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_l2c_check_state_result];
inline bool packetl2c_check_state_result::has_packet_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packetl2c_check_state_result::set_has_packet_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packetl2c_check_state_result::clear_has_packet_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packetl2c_check_state_result::clear_packet_id() {
  packet_id_ = 15004;
  clear_has_packet_id();
}
inline ::fish_protocols::e_server_msg_type packetl2c_check_state_result::packet_id() const {
  return static_cast< ::fish_protocols::e_server_msg_type >(packet_id_);
}
inline void packetl2c_check_state_result::set_packet_id(::fish_protocols::e_server_msg_type value) {
  assert(::fish_protocols::e_server_msg_type_IsValid(value));
  set_has_packet_id();
  packet_id_ = value;
}

// optional bool is_intable = 2 [default = false];
inline bool packetl2c_check_state_result::has_is_intable() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void packetl2c_check_state_result::set_has_is_intable() {
  _has_bits_[0] |= 0x00000002u;
}
inline void packetl2c_check_state_result::clear_has_is_intable() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void packetl2c_check_state_result::clear_is_intable() {
  is_intable_ = false;
  clear_has_is_intable();
}
inline bool packetl2c_check_state_result::is_intable() const {
  return is_intable_;
}
inline void packetl2c_check_state_result::set_is_intable(bool value) {
  set_has_is_intable();
  is_intable_ = value;
}

// repeated .fish_protocols.msg_item itemlist = 3;
inline int packetl2c_check_state_result::itemlist_size() const {
  return itemlist_.size();
}
inline void packetl2c_check_state_result::clear_itemlist() {
  itemlist_.Clear();
}
inline const ::fish_protocols::msg_item& packetl2c_check_state_result::itemlist(int index) const {
  return itemlist_.Get(index);
}
inline ::fish_protocols::msg_item* packetl2c_check_state_result::mutable_itemlist(int index) {
  return itemlist_.Mutable(index);
}
inline ::fish_protocols::msg_item* packetl2c_check_state_result::add_itemlist() {
  return itemlist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::fish_protocols::msg_item >&
packetl2c_check_state_result::itemlist() const {
  return itemlist_;
}
inline ::google::protobuf::RepeatedPtrField< ::fish_protocols::msg_item >*
packetl2c_check_state_result::mutable_itemlist() {
  return &itemlist_;
}

// optional int32 turret_id = 4;
inline bool packetl2c_check_state_result::has_turret_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void packetl2c_check_state_result::set_has_turret_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void packetl2c_check_state_result::clear_has_turret_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void packetl2c_check_state_result::clear_turret_id() {
  turret_id_ = 0;
  clear_has_turret_id();
}
inline ::google::protobuf::int32 packetl2c_check_state_result::turret_id() const {
  return turret_id_;
}
inline void packetl2c_check_state_result::set_turret_id(::google::protobuf::int32 value) {
  set_has_turret_id();
  turret_id_ = value;
}

// optional int32 gamelvl = 5;
inline bool packetl2c_check_state_result::has_gamelvl() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void packetl2c_check_state_result::set_has_gamelvl() {
  _has_bits_[0] |= 0x00000010u;
}
inline void packetl2c_check_state_result::clear_has_gamelvl() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void packetl2c_check_state_result::clear_gamelvl() {
  gamelvl_ = 0;
  clear_has_gamelvl();
}
inline ::google::protobuf::int32 packetl2c_check_state_result::gamelvl() const {
  return gamelvl_;
}
inline void packetl2c_check_state_result::set_gamelvl(::google::protobuf::int32 value) {
  set_has_gamelvl();
  gamelvl_ = value;
}

// optional int32 gameexp = 6;
inline bool packetl2c_check_state_result::has_gameexp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void packetl2c_check_state_result::set_has_gameexp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void packetl2c_check_state_result::clear_has_gameexp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void packetl2c_check_state_result::clear_gameexp() {
  gameexp_ = 0;
  clear_has_gameexp();
}
inline ::google::protobuf::int32 packetl2c_check_state_result::gameexp() const {
  return gameexp_;
}
inline void packetl2c_check_state_result::set_gameexp(::google::protobuf::int32 value) {
  set_has_gameexp();
  gameexp_ = value;
}

// optional int32 getgift = 7;
inline bool packetl2c_check_state_result::has_getgift() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void packetl2c_check_state_result::set_has_getgift() {
  _has_bits_[0] |= 0x00000040u;
}
inline void packetl2c_check_state_result::clear_has_getgift() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void packetl2c_check_state_result::clear_getgift() {
  getgift_ = 0;
  clear_has_getgift();
}
inline ::google::protobuf::int32 packetl2c_check_state_result::getgift() const {
  return getgift_;
}
inline void packetl2c_check_state_result::set_getgift(::google::protobuf::int32 value) {
  set_has_getgift();
  getgift_ = value;
}

// -------------------------------------------------------------------

// packetc2l_use_item

// optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_c2l_use_item];
inline bool packetc2l_use_item::has_packet_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packetc2l_use_item::set_has_packet_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packetc2l_use_item::clear_has_packet_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packetc2l_use_item::clear_packet_id() {
  packet_id_ = 10106;
  clear_has_packet_id();
}
inline ::fish_protocols::e_server_msg_type packetc2l_use_item::packet_id() const {
  return static_cast< ::fish_protocols::e_server_msg_type >(packet_id_);
}
inline void packetc2l_use_item::set_packet_id(::fish_protocols::e_server_msg_type value) {
  assert(::fish_protocols::e_server_msg_type_IsValid(value));
  set_has_packet_id();
  packet_id_ = value;
}

// optional int32 item_id = 2;
inline bool packetc2l_use_item::has_item_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void packetc2l_use_item::set_has_item_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void packetc2l_use_item::clear_has_item_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void packetc2l_use_item::clear_item_id() {
  item_id_ = 0;
  clear_has_item_id();
}
inline ::google::protobuf::int32 packetc2l_use_item::item_id() const {
  return item_id_;
}
inline void packetc2l_use_item::set_item_id(::google::protobuf::int32 value) {
  set_has_item_id();
  item_id_ = value;
}

// optional int32 pos_x = 3;
inline bool packetc2l_use_item::has_pos_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void packetc2l_use_item::set_has_pos_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void packetc2l_use_item::clear_has_pos_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void packetc2l_use_item::clear_pos_x() {
  pos_x_ = 0;
  clear_has_pos_x();
}
inline ::google::protobuf::int32 packetc2l_use_item::pos_x() const {
  return pos_x_;
}
inline void packetc2l_use_item::set_pos_x(::google::protobuf::int32 value) {
  set_has_pos_x();
  pos_x_ = value;
}

// optional int32 pos_y = 4;
inline bool packetc2l_use_item::has_pos_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void packetc2l_use_item::set_has_pos_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void packetc2l_use_item::clear_has_pos_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void packetc2l_use_item::clear_pos_y() {
  pos_y_ = 0;
  clear_has_pos_y();
}
inline ::google::protobuf::int32 packetc2l_use_item::pos_y() const {
  return pos_y_;
}
inline void packetc2l_use_item::set_pos_y(::google::protobuf::int32 value) {
  set_has_pos_y();
  pos_y_ = value;
}

// -------------------------------------------------------------------

// packetl2c_use_item_result

// optional .fish_protocols.e_server_msg_type packet_id = 1 [default = e_mst_l2c_use_item_result];
inline bool packetl2c_use_item_result::has_packet_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void packetl2c_use_item_result::set_has_packet_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void packetl2c_use_item_result::clear_has_packet_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void packetl2c_use_item_result::clear_packet_id() {
  packet_id_ = 15211;
  clear_has_packet_id();
}
inline ::fish_protocols::e_server_msg_type packetl2c_use_item_result::packet_id() const {
  return static_cast< ::fish_protocols::e_server_msg_type >(packet_id_);
}
inline void packetl2c_use_item_result::set_packet_id(::fish_protocols::e_server_msg_type value) {
  assert(::fish_protocols::e_server_msg_type_IsValid(value));
  set_has_packet_id();
  packet_id_ = value;
}

// optional int32 item_id = 2;
inline bool packetl2c_use_item_result::has_item_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void packetl2c_use_item_result::set_has_item_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void packetl2c_use_item_result::clear_has_item_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void packetl2c_use_item_result::clear_item_id() {
  item_id_ = 0;
  clear_has_item_id();
}
inline ::google::protobuf::int32 packetl2c_use_item_result::item_id() const {
  return item_id_;
}
inline void packetl2c_use_item_result::set_item_id(::google::protobuf::int32 value) {
  set_has_item_id();
  item_id_ = value;
}

// optional .msg_type_def.e_msg_result_def result = 3 [default = e_rmt_fail];
inline bool packetl2c_use_item_result::has_result() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void packetl2c_use_item_result::set_has_result() {
  _has_bits_[0] |= 0x00000004u;
}
inline void packetl2c_use_item_result::clear_has_result() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void packetl2c_use_item_result::clear_result() {
  result_ = 2;
  clear_has_result();
}
inline ::msg_type_def::e_msg_result_def packetl2c_use_item_result::result() const {
  return static_cast< ::msg_type_def::e_msg_result_def >(result_);
}
inline void packetl2c_use_item_result::set_result(::msg_type_def::e_msg_result_def value) {
  assert(::msg_type_def::e_msg_result_def_IsValid(value));
  set_has_result();
  result_ = value;
}

// optional int32 item_count = 4 [default = 1];
inline bool packetl2c_use_item_result::has_item_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void packetl2c_use_item_result::set_has_item_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void packetl2c_use_item_result::clear_has_item_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void packetl2c_use_item_result::clear_item_count() {
  item_count_ = 1;
  clear_has_item_count();
}
inline ::google::protobuf::int32 packetl2c_use_item_result::item_count() const {
  return item_count_;
}
inline void packetl2c_use_item_result::set_item_count(::google::protobuf::int32 value) {
  set_has_item_count();
  item_count_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace fish_protocols

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_fish_5fcrazy_5fprotocol_2eproto__INCLUDED
