// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cows_def.proto

#ifndef PROTOBUF_cows_5fdef_2eproto__INCLUDED
#define PROTOBUF_cows_5fdef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace cows_protocols {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cows_5fdef_2eproto();
void protobuf_AssignDesc_cows_5fdef_2eproto();
void protobuf_ShutdownFile_cows_5fdef_2eproto();


enum e_server_msg_type {
  e_mst_start_c2l = 10000,
  e_mst_c2l_get_room_info = 10001,
  e_mst_c2l_enter_table = 10002,
  e_mst_c2l_leave_table = 10003,
  e_mst_c2l_check_state = 10004,
  e_mst_c2l_get_scene_info = 10010,
  e_mst_c2l_ask_bet_info = 10011,
  e_mst_c2l_ask_apply_banker = 10012,
  e_mst_c2l_ask_leave_banker = 10013,
  e_mst_c2l_ask_bankerlist = 10014,
  e_mst_c2l_ask_history_info = 10015,
  e_mst_c2l_ask_continue_bet = 10016,
  e_mst_c2l_ask_clear_bet = 10017,
  e_mst_c2l_ask_playerlist = 10018,
  e_mst_c2l_ask_snatch_banker = 10019,
  e_mst_c2l_leave_list_banker = 10020,
  e_mst_c2l_debug = 10100,
  e_mst_start_l2c = 15000,
  e_mst_l2c_get_room_info_result = 15001,
  e_mst_l2c_enter_table_result = 15002,
  e_mst_l2c_leave_table_result = 15003,
  e_mst_l2c_check_state_result = 15004,
  e_mst_l2c_get_scene_info_result = 15010,
  e_mst_l2c_bet_info_result = 15011,
  e_mst_l2c_apply_banker_result = 15012,
  e_mst_l2c_leave_banker_result = 15013,
  e_mst_l2c_bankerlist_result = 15014,
  e_mst_l2c_history_info = 15015,
  e_mst_l2c_banker_info = 15016,
  e_mst_l2c_continue_bet_result = 15017,
  e_mst_l2c_clear_bet_result = 15018,
  e_mst_l2c_playerlist_result = 15019,
  e_mst_l2c_snatch_banker_result = 15020,
  e_mst_l2c_banker_success = 15021,
  e_mst_l2c_bc_scene_prepare_into = 15050,
  e_mst_l2c_bc_scene_bet_into = 15051,
  e_mst_l2c_bc_sync_scene_bet_into = 15052,
  e_mst_l2c_bc_scene_deal_into = 15053,
  e_mst_l2c_bc_scene_result_into = 15054,
  e_mst_l2c_bc_snatch_banker = 15055,
  e_mst_l2c_notify_sceneinfo = 15101,
  e_mst_l2c_debug_result = 15102,
  e_mst_l2c_leave_list_banker = 15103,
  e_mst_attention_needLeave = 15104,
  e_mst_clend_index = 20000
};
bool e_server_msg_type_IsValid(int value);
const e_server_msg_type e_server_msg_type_MIN = e_mst_start_c2l;
const e_server_msg_type e_server_msg_type_MAX = e_mst_clend_index;
const int e_server_msg_type_ARRAYSIZE = e_server_msg_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_server_msg_type_descriptor();
inline const ::std::string& e_server_msg_type_Name(e_server_msg_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_server_msg_type_descriptor(), value);
}
inline bool e_server_msg_type_Parse(
    const ::std::string& name, e_server_msg_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_server_msg_type>(
    e_server_msg_type_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace cows_protocols

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cows_protocols::e_server_msg_type>() {
  return ::cows_protocols::e_server_msg_type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cows_5fdef_2eproto__INCLUDED
