// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_5dragons_def.proto

#ifndef PROTOBUF_game_5f5dragons_5fdef_2eproto__INCLUDED
#define PROTOBUF_game_5f5dragons_5fdef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace game_5dragons_protocols {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_game_5f5dragons_5fdef_2eproto();
void protobuf_AssignDesc_game_5f5dragons_5fdef_2eproto();
void protobuf_ShutdownFile_game_5f5dragons_5fdef_2eproto();


enum e_server_msg_type {
  e_mst_start_c2l = 10000,
  e_mst_c2l_check_state = 10001,
  e_mst_c2l_enter_game = 10002,
  e_mst_c2l_leave_game = 10003,
  e_mst_c2l_star_game = 10004,
  e_mst_c2l_buy_lv = 10005,
  e_mst_c2l_double_game = 10006,
  e_mst_c2l_buy_double_times = 10007,
  e_mst_c2l_test_game = 10008,
  e_mst_start_l2c = 15000,
  e_mst_l2c_check_state_result = 15001,
  e_mst_l2c_enter_game_result = 15002,
  e_mst_l2c_leave_game_result = 15003,
  e_mst_l2c_star_game_result = 15004,
  e_mst_l2c_buy_lv_result = 15005,
  e_mst_l2c_double_game_result = 15006,
  e_mst_l2c_buy_double_times_result = 15007,
  e_mst_l2c_test_game_result = 15008,
  e_mst_l2c_debuginfo = 15009,
  e_mst_clend_index = 20000
};
bool e_server_msg_type_IsValid(int value);
const e_server_msg_type e_server_msg_type_MIN = e_mst_start_c2l;
const e_server_msg_type e_server_msg_type_MAX = e_mst_clend_index;
const int e_server_msg_type_ARRAYSIZE = e_server_msg_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_server_msg_type_descriptor();
inline const ::std::string& e_server_msg_type_Name(e_server_msg_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_server_msg_type_descriptor(), value);
}
inline bool e_server_msg_type_Parse(
    const ::std::string& name, e_server_msg_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_server_msg_type>(
    e_server_msg_type_descriptor(), name, value);
}
enum e_dragons_type {
  big_paradise = 1,
  small_paradise = 2,
  normal = 3,
  big_hell = 4,
  small_hell = 5
};
bool e_dragons_type_IsValid(int value);
const e_dragons_type e_dragons_type_MIN = big_paradise;
const e_dragons_type e_dragons_type_MAX = small_hell;
const int e_dragons_type_ARRAYSIZE = e_dragons_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_dragons_type_descriptor();
inline const ::std::string& e_dragons_type_Name(e_dragons_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_dragons_type_descriptor(), value);
}
inline bool e_dragons_type_Parse(
    const ::std::string& name, e_dragons_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_dragons_type>(
    e_dragons_type_descriptor(), name, value);
}
enum e_double_tag {
  e_save_tag = 0,
  e_spades_tag = 1,
  e_hearts_tag = 2,
  e_plum_flower_tag = 3,
  e_square_piece_tag = 4,
  e_red_tag = 5,
  e_black_tag = 6
};
bool e_double_tag_IsValid(int value);
const e_double_tag e_double_tag_MIN = e_save_tag;
const e_double_tag e_double_tag_MAX = e_black_tag;
const int e_double_tag_ARRAYSIZE = e_double_tag_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_double_tag_descriptor();
inline const ::std::string& e_double_tag_Name(e_double_tag value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_double_tag_descriptor(), value);
}
inline bool e_double_tag_Parse(
    const ::std::string& name, e_double_tag* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_double_tag>(
    e_double_tag_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_5dragons_protocols

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_5dragons_protocols::e_server_msg_type>() {
  return ::game_5dragons_protocols::e_server_msg_type_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_5dragons_protocols::e_dragons_type>() {
  return ::game_5dragons_protocols::e_dragons_type_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::game_5dragons_protocols::e_double_tag>() {
  return ::game_5dragons_protocols::e_double_tag_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_5f5dragons_5fdef_2eproto__INCLUDED
